steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://AmitPotdukhe07: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@github.com/AmitPotdukhe07/rd-df-Information-Pipelines.git']
  dir: /workspace

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--recurse', '/workspace/rd-df-Information-Pipelines/*', 'rd-df-pipelines:/root/cicd_test']
