steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
        # Retrieve the SSH key from Secret Manager
        gcloud secrets versions access latest --secret=my-ssh-key > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa

        # Add SSH key to the SSH agent
        eval "$(ssh-agent -s)"
        ssh-add /root/.ssh/id_rsa

        # Disable strict host key checking to avoid host key verification errors
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config

        # SSH into the VM instance
        gcloud compute ssh rd-df-pipelines --zone=us-central1-c --project=reviewdale-datafabric --ssh-key-file=/root/.ssh/id_rsa

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--recurse', '/workspace/vercel-clone/*', 'rd-df-pipelines:/root/cicd_test', '--zone=us-central1-c']
