# List the contents of the workspace to verify the source has been provided by the trigger
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Listing contents of /workspace:"
      ls -la /workspace

# Retrieve the private key from Secret Manager
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Retrieving private key from Secret Manager..."
      gcloud secrets versions access latest --secret=rd-df-vm-private-key > /workspace/vm-key.pem
      chmod 600 /workspace/vm-key.pem

# Copy the code to the VM using gcloud scp with private key and amitpotdukhe as the username
# Copy only the files inside the directory to the VM
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      for file in /workspace/*; do
        if [ -f "$file" ] || [ -d "$file" ]; then
          gcloud compute scp --recurse "$file" amitpotdukhe@rd-vm-df-pipelines:/home/amitpotdukhe/cicd_test --zone asia-south1-c
        fi
      done

# Manually perform SSH using the private key to copy files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Copying files via SSH..."
      scp -i /workspace/vm-key.pem -o StrictHostKeyChecking=no -r /workspace amitpotdukhe@rd-vm-df-pipelines:/root/cicd_test

timeout: '1800s'
