steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://AmitPotdukhe07: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@github.com/AmitPotdukhe07/vercel-clone.git']
  dir: /workspace

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
        echo $SSH_KEY > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        gcloud compute ssh rd-df-pipelines --zone=us-central1-c --project=reviewdale-datafabric --ssh-key-file=/root/.ssh/id_rsa

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--recurse', '/workspace/vercel-clone/*', 'rd-df-pipelines:/root/cicd_test', '--zone=us-central1-c']
